# Generated by Django 3.0 on 2024-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_auto_20210713_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_url',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
